name: Update Strava Activities

on:
  push:
    branches:
      - main
  schedule:
    # Run every Sunday at 23:00 GMT (11 PM)
    - cron: '0 23 * * 0'
  workflow_dispatch:

# Prevent overlapping runs (manual + scheduled) for same workflow
concurrency:
  group: update-activities
  cancel-in-progress: false

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-activities:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Fetch Strava activities
        env:
          STRAVA_CLIENT_ID: ${{ vars.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        run: npm run fetch-activities
        
      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-static
          path: static
          if-no-files-found: error
          retention-days: 1

  deploy-pages:
    needs: update-activities
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Download site artifact
        uses: actions/download-artifact@v5
        with:
          name: site-static
          path: static

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: static
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4